# Generated by Django 2.0.9 on 2018-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresults',
            old_name='title',
            new_name='search',
        ),
        migrations.RemoveField(
            model_name='searchresults',
            name='desc',
        ),
    ]
