# Generated by Django 2.0.9 on 2018-10-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181012_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='search',
            field=models.ManyToManyField(to='App.Broadcast', verbose_name='Результаты'),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Поиск'),
        ),
    ]
