# Generated by Django 2.0.9 on 2018-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181012_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='word',
            field=models.CharField(max_length=500, verbose_name='Поиск'),
        ),
    ]
